clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    - vault
    - golang-external-secrets
    - inferencing-app
    - storage
    - redhat-ods-operator:
        operatorGroup: true
        targetNamespaces: []
    - openshift-serverless:
        operatorGroup: true
        targetNamespaces: []

  projects:
    - hub
    - rhods
    - inferencing-app
    - storage

  subscriptions:
    rhods:
      name: rhods-operator
      namespace: redhat-ods-operator
      channel: stable

    servicemesh:
      name: servicemeshoperator
      namespace: openshift-operators
      channel: stable

    serverless:
      name: serverless-operator
      namespace: openshift-serverless
      channel: stable

  applications:
    vault:
      name: vault
      namespace: vault
      project: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      chart: golang-external-secrets
      chartVersion: 0.1.*

    # rhods:
    #   name: rhods
    #   namespace: redhat-ods-operator
    #   project: rhods
    #   path: charts/rhods

    inferencing-app:
      name: inferencing-app
      namespace: inferencing-app
      project: inferencing-app
      path: charts/inferencing-app

    storage:
      name: storage
      namespace: storage
      project: storage
      path: charts/storage
