apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: fraud-detection
spec:
  dspVersion: v2
  apiServer:
    enableSamplePipeline: false
    cABundle:
      configMapKey: ca.crt
      configMapName: kube-root-ca.crt
  objectStorage:
    enableExternalRoute: true
    externalStorage:
      bucket: pipeline-artifacts
      host: minio-s3-fraud-detection.apps.drew-rhoai.aws.validatedpatterns.io
      region: us-east-1
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: aws-connection-pipeline-artifacts
      scheme: https
  mlpipelineUI:
    image: quay.io/opendatahub/ds-pipelines-frontend:latest
