apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      scrapeInterval: 5s
      nodeSelector:
        prometheus: "true"
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "prometheus"
          effect: "NoSchedule"
