name: mlops-kubeflow-pipelines
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - kfp
  - pip
  - pip:
    - kfp-kubernetes
    - numpy==2.2.5
    - pandas==2.2.3
    - torch==2.6.0
    - scikit-learn==1.6.1
    - boto3==1.37.38
    - botocore==1.37.38
