name: mlops-kubeflow-pipelines
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - boto3==1.35.55
    - botocore==1.35.55
    - keras==2.15.0
    - kfp==2.5.0
    - kfp-kubernetes==1.0.0
    - numpy==1.26.4
    - onnx==1.17.0
    - onnxruntime==1.19.2
    - pandas==2.2.2
    - scikit-learn==1.4.2
    - tensorflow==2.15.1
    - tf2onnx==1.16.1
