apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storage.fullname" . }}
  namespace: {{ .Values.storage.namespace | default .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: {{ include "storage.fullname" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "storage.fullname" . }}
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ printf "%s-pv-claim" (include "storage.fullname" .) }}
      initContainers:
        - name: create-buckets
          image: busybox:1.28
          command:
            - "sh"
            - "-c"
            - {{ printf "mkdir -p /storage/%s" .Values.storage.bucket | quote }}
          volumeMounts:
            - name: storage
              mountPath: "/storage"
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /storage
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.secretName }}
                  key: access_key_id
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.secretName }}
                  key: access_key_secret
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: storage
              mountPath: "/storage"
