apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-pv-claim" (include "storage.fullname" .) }}
  namespace: {{ .Values.storage.namespace | default .Release.Namespace | quote }}
  labels:
    app: {{ printf "%s-storage-claim" (include "storage.fullname" .) }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
