apiVersion: v1
kind: Service
metadata:
  name: {{ include "storage.fullname" . }}
  namespace: {{ .Values.storage.namespace | default .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: api
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: console
  selector:
    app: {{ include "storage.fullname" . }}
