{{- if .Values.crunchyPostgres.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
data:
  init.sql: |
    \c {{ include "mlflow-server.fullname" . }}
    GRANT CREATE ON SCHEMA public TO "{{ include "mlflow-server.fullname" . }}";
{{- end }}