apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minio
    component: minio
  name: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.storageSize | default "10Gi" }}
