apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    component: minio
  name: minio
spec:
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9090
      targetPort: 9090
  selector:
    app: minio
    component: minio
  type: ClusterIP
